site_name: My Docs
site_url: https://zealexorcist.github.io/blog/
nav:
  - Home: index.md
  - About: about.md
  - Blog: 
    - blog/index.md
  - Tags: blog/tags.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/radiation
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.footer
    - navigation.indexes
    
plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Cryptography
        - Python
        - General
        - Forensics
        - Web
        - AI
  - tags:
      tags_file: blog/tags.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: simple/github
      link: https://github.com/ZealExorcist
    - icon: simple/linkedin
      link: https://linkedin.com/in/rohan-nayakanti
    - icon: simple/gmail
      link: mailto:rohan.nayakanti@gmail.com